### ISSUE TITLE
prasing whole workshop

### ISSUE THREAD

**Issue by bukowa** [CarlFlo/steamWorkshopParser#1]
Hey did you think about parsing whole workshop for a game to gather all mods?

**Comment by CarlFlo** [comment]
This is just for downloading a mod, not for browsing mods. I think it would be more convenient to use the Steam client if you want to look for mods

**Comment by bukowa** [comment]
I understand, is there a way to create new service that given steam workshop game url would return a list of all steamid mods for example?

**Comment by CarlFlo** [comment]
That is possible. That would be a web scraper that would iterate over every page containing workshop items. Such a feature would be out of scope for this project. But it sounds pretty simple to code up. What do you need it for?

**Comment by CarlFlo** [comment]
I made a new project that I hope will do what you wanted https://github.com/CarlFlo/steamGameWorkshopCollector

**Comment by bukowa** [comment]
> That is possible. That would be a web scraper that would iterate over every page containing workshop items. Such a feature would be out of scope for this project. But it sounds pretty simple to code up. What do you need it for?

I were looking for implementing it via gRPC server just like this project does. That's why I asked.
I am looking to scrape all mods for indexing and searching while developing own mods. For reference basically. *what other people did and how

> I made a new project that I hope will do what you wanted https://github.com/CarlFlo/steamGameWorkshopCollector

Thank you!

**Comment by CarlFlo** [comment]
Ah I see. I hope my code can be of some use to you :)

**Comment by bukowa** [comment]
> Ah I see. I hope my code can be of some use to you :)

Just tested thank you a lot gonna save time!
